### ISSUE TITLE
Unable to profile on Java 8

### ISSUE THREAD

**Issue by lehvolk** [parttimenerd/intellij-profiler-plugin#10]
On attempt to profile project binded to Java 8 I've got such error:

```
> "C:\Program Files\Amazon Corretto\jdk1.8.0_332\bin\java.exe" -XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints "-XX:StartFlightRecording=filename=D:\work\jacodb\profile.jfr,settings='profile',dumponexit=true" -Xlog:jfr+startup=errororg.jacodb.testing.performance.TakeMemoryDumpKt
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Unrecognized option: -Xlog:jfr+startup=error

Process finished with exit code 1
```

It's up to maintainer to decide whenever this is bug or feature. But if it's feature then probably there should be more user-friendly error or run configuration should be not available.

**Comment by parttimenerd** [comment]
This is clearly a bug. Could you send me the output of `java -version` on your system?

**Comment by lehvolk** [comment]
> .\java.exe -version
openjdk version "1.8.0_332"
OpenJDK Runtime Environment Corretto-8.332.08.1 (build 1.8.0_332-b08)
OpenJDK 64-Bit Server VM Corretto-8.332.08.1 (build 25.332-b08, mixed mode)

**Comment by parttimenerd** [comment]
Thanks. I hope I fixed your error.
