### ISSUE TITLE
Does not work with oracle jdk 11.0.6 and earlier 

### ISSUE THREAD

**Issue by jinwik** [parttimenerd/intellij-profiler-plugin#13]
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8213617

`val pid = jvmInformation?.getLong("pid") ?: -1`

**Comment by parttimenerd** [comment]
Thanks, I'll merge your jfrtofp PR and keep this issue open till I pushed a new version of this plugin (probably in the next few days).
