### ISSUE TITLE
Firefox Profiler could not download the profile? Cannot view profile.jfr

### ISSUE THREAD

**Issue by tkb2022** [parttimenerd/intellij-profiler-plugin#14]
Hi! I am extremely new to Profilers and would like some help if you have any insight - I have followed the steps [here](https://github.com/firefox-devtools/profiler#development) to install and run Firefox Profiler locally and it seems to be successfully running.
<img width="655" alt="image" src="https://user-images.githubusercontent.com/119710352/220547567-bcc7988d-246c-4949-85c5-5715993720ca.png">

Then I try running my application with "Profile with async-profiler" from your Intellij plugin but then when I stop the run and expect the profile.jfr to be opened and look like the call tree in your Plugin homepage picture, it instead shows:
![image](https://user-images.githubusercontent.com/119710352/220547880-7901425e-4dc1-4147-8d7e-ff6a3aeefc11.png)

I also tried opening profile.jfr in FlameViewer but for some unknown reason it shows the error "File was not sent". 

For reference, I am on macOS. Please let me know if there is any advice for this. Thanks so much!!

**Comment by parttimenerd** [comment]
Could you give my the profile.jfr file?

**Comment by tkb2022** [comment]
I can go on a separate account to create and post one as this was created on a confidential system but I have also tried using your plugin with the Quarkus QuickStart project (https://quarkus.io/guides/getting-started) and using a GET call to http://localhost:8080/hello but I still face the same issue with the profile.jfr as above.

**Comment by parttimenerd** [comment]
Thanks. I can reproduce the issue and tackle it tomorrow morning.

**Comment by parttimenerd** [comment]
Thanks, I totally forgot about the issue. I'll be working on it next week.

**Comment by bademux** [comment]
the same here 
[profile.jfr.zip](https://github.com/parttimenerd/intellij-profiler-plugin/files/14501802/profile.jfr.zip)

**Comment by parttimenerd** [comment]
Thanks. I'm at the conference on Thursday but will make it in March to look into these issues. I'm happy for any PRs...

**Comment by parttimenerd** [comment]
Fixed it in jfrtofp

**Comment by parttimenerd** [comment]
I'll publish a new version next week after fixing #24

**Comment by parttimenerd** [comment]
It should hopefully all be fixed and the new version is on the JetBrains marketplace.
