### ISSUE TITLE
IntelliJ EAP version support

### ISSUE THREAD

**Issue by sureshg** [parttimenerd/intellij-profiler-plugin#15]
Lot of folks are on IntelliJ EAP versions for daily usage and would be great to have support for EAP versions too.

Current EAP version is, `IntelliJ IDEA 2023.1 EAP (Ultimate Edition)`

**Comment by parttimenerd** [comment]
I think that into #6. I'll look into the next few days.

**Comment by parttimenerd** [comment]
Fixed with #20 and published in the market place.
