### ISSUE TITLE
Profiling from script

### ISSUE THREAD

**Issue by skin27** [parttimenerd/intellij-profiler-plugin#16]
I have the following Java application:

1. JDK 11 (Ecliple Temurin).
2. Gradle 8.1 (Build tool)
3. Intellij Profiler Plugin 0.0.8
4. IntelliJ (IntelliJ IDEA 2023.1.2 (Community Edition)
5. Windows 10

In IntelliJ I have a run configuration that runs Gradle (build & run) from a batch script. When I run the configuration with "Run --> Profile.." the applications runs normally, but I have no options to profile or view the profile. In the readme it says "And opens the profile automatically afterwards.". What does the this mean? Currently nothing is opened automatically. Should that be done during run/profiling or when stop the application? Can I get more information/debug info?

**Comment by parttimenerd** [comment]
Using a gradle or maven build target might currently be unsupported, thanks for pointing this out.

> What does the this mean? Currently nothing is opened automatically.

That's clearly a bug that I have to address.

**Comment by parttimenerd** [comment]
I finally found the time to work on the support of gradle and maven (and `mvn quarkus:dev` and spring boot builds). I'll finish it tomorrow(ish).
