### ISSUE TITLE
Intellij 2023.2.2 support

### ISSUE THREAD

**Issue by xhanin** [parttimenerd/intellij-profiler-plugin#18]
The plugin version 0.0.8 is declared as compatible with Intellij up to 2023.1.5 only, so we can't install it from the marketplace on intellij 2023.2.

**Comment by parttimenerd** [comment]
Good catch, I'll fix it today/tomorrow.

**Comment by xhanin** [comment]
Excellent, thanks!

**Comment by parttimenerd** [comment]
I merged #17 and pushed the release, you should find it in the marketplace.
