### ISSUE TITLE
Gracefully handle `async-profiler` "No AllocTracer symbols found" failures

### ISSUE THREAD

**Issue by I-Al-Istannen** [parttimenerd/intellij-profiler-plugin#8]
Hey,

I had a usecase for this today but it always failed with 
```
Error: Could not fetch the profile on remote server. Response was: 500 Server Error.
The full stack has been written to the Web Console.
```

After dejectedly solving my problem like a caveman using printf debugging instead, I decided to have a closer look. Apparently async-profiler could not do allocation tracing (on my openjdk 19 build without debug symbols) and therefore doesn't capture anything except a few marker symbols. IntelliJ can not open the resulting jfr file, your server crashed in jdk JFR reading code while converting it, and in general there isn't much to be found in there.

I am not sure why this is even a problem as https://github.com/jvm-profiling-tools/async-profiler/issues/193 says it should work anyways, but you might want to handle that error a bit more gracefully. Manually disabling alloc tracing in the generated config (or only using JFR) solves the problem. Maybe you want to tell the user to disable it or offer to disable it for them?

One of those days I will need to build my own jdk, I don't quite understand why arch doesn't offer any debug symbol package :(

Enjoy your night :P

----

<details>

<summary>async-profiler error</summary>

```
[WARN] Install JVM debug symbols to improve profile accuracy
[ERROR] No AllocTracer symbols found. Are JDK debug symbols installed?
```

</details>

**Comment by parttimenerd** [comment]
> After dejectedly solving my problem like a caveman using printf debugging instead, I decided to have a closer look. Apparently async-profiler could not do allocation tracing (on my openjdk 19 build without debug symbols) and therefore doesn't capture anything except a few marker symbols. IntelliJ can not open the resulting jfr file, your server crashed in jdk JFR reading code while converting it, and in general there isn't much to be found in there.

That's definitely weird. Maybe I can detect it programmatically, so I can just disable async-profiler on these platforms? Any ideas how to do this?

> One of those days I will need to build my own jdk, I don't quite understand why arch doesn't offer any debug symbol package :(

Yeah, I have to build my own all the time. You could look into sdkman, maybe they ship debug symbols.

**Comment by parttimenerd** [comment]
It's an interesting problem and it is possibly a bug in async-profiler.

**Comment by I-Al-Istannen** [comment]
> That's definitely weird. Maybe I can detect it programmatically, so I can just disable async-profiler on these platforms? Any ideas how to do this?

I would like to use it though. Not with allocation profiling then, but I was mainly interested in CPU profiles anyways. I guess you could maybe look at the output, but that sounds a bit brittle. Alternatively you could have a look at the converter error and treat that as a "you might want to disable allocation tracing?" or "The converter failed, are you sure your input is actually valid? Have a look at the async-profiler output window."

Here is the failing created profile [jfr.zip](https://github.com/parttimenerd/intellij-profiler-plugin/files/10701094/jfr.zip). You can just open it in IJ and it should:tm: crash.

> Yeah, I have to build my own all the time. You could look into sdkman, maybe they ship debug symbols.

I didn't see any in sdkman and using shipilevs fastdebugbuild the JVM aborts with an internal error (always, not just during profiling)
```
# To suppress the following error report, specify this argument
# after -XX: or in .hotspotrc:  SuppressErrorAt=/linkResolver.cpp:177
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (../../src/hotspot/share/interpreter/linkResolver.cpp:177), pid=529961, tid=529962
#  assert(index == Method::nonvirtual_vtable_index || index >= 0) failed: bad index -3
```
That hole is a bit too deep for my current amount of free time :P It works without allocation profiling, I am happy with that for now. I guess I will find out how to marry my distro packaging with debug symbols some other time

> It's an interesting problem and it is possibly a bug in async-profiler.

It sounds a bit odd to just throw up your hands and die if one tracing type doesn't work, but I also haven't dug into async-profiler much.

**Comment by parttimenerd** [comment]
I probably just misused async-profiler. Andrei Pangin told me that I should use `alloc` with a threshold so that the ObjectSampler is used instead of the AllocationSampler (i.e. `alloc=512k`). I fix it tomorrow.

> I didn't see any in sdkman and using shipilevs fastdebugbuild the JVM aborts with an internal error (always, not just during profiling)

I would like to have the hserr file, so I can fix this assertion.

**Comment by I-Al-Istannen** [comment]
Sounds good :)

> I would like to have the hserr file, so I can fix this assertion.

This probably? [hs_err.zip](https://github.com/parttimenerd/intellij-profiler-plugin/files/10701844/hs_err.zip)

**Comment by parttimenerd** [comment]
The assertion seems to be independent from async-profiler. You could report an error to the OpenJDK if you like.

**Comment by I-Al-Istannen** [comment]
Yes, that is what I meant with `(always, not just during profiling)` in my last message :)

It mostly served as justification for "I am unable to verify anything works if I get debug symbols, as I can't obtain a JDK with them currently". I should have worded that better.

> You could report an error to the OpenJDK if you like.

Maybe, I will see. It's probably not critical… The application works using a release build JDK of the same version. Bad heuristic, I know :P

Have a nice night :lady_beetle:

**Comment by parttimenerd** [comment]
Ups, I'm a bit tired. I fix the error in my plugin tomorrow morning.
