### ISSUE TITLE
Profiling tests issues

### ISSUE THREAD

**Issue by lehvolk** [parttimenerd/intellij-profiler-plugin#9]
Profile with JFR run configuration is available for Test classes and tests itself. But after run there is no tab opened and there is no profile.jfr in source root. 

I use gradle runner for tests.

**Comment by parttimenerd** [comment]
Could you give me the text in the "Profiling [...]" tab in the lower part of the IDE?
![image](https://user-images.githubusercontent.com/490655/217857830-33f69f01-5d60-4a54-893c-6a9957b27a21.png)

**Comment by lehvolk** [comment]
This is my gradle settings
![image](https://user-images.githubusercontent.com/6284727/218043060-b305902e-b778-4591-a743-d0630de1251a.png)

I'm running regular test:
![image](https://user-images.githubusercontent.com/6284727/218043334-20e9bdd6-62d9-468b-847c-5ae32496c95f.png)


This is output in output tab. There is nothing related to jfr dump:
![image](https://user-images.githubusercontent.com/6284727/218043564-61a4fbda-ea34-4ea5-be68-0144469ac824.png)

Small remark. At the moment I'm using IDEA Ultimate in my daily work but I want to downgrade to Community edition. Ability to profile apps is an only reason for staying on Ultimate. Thanks a lot for you efforts.

**Comment by parttimenerd** [comment]
Thanks for the screenshots. I can reproduce the issue with a minimal project.
